# Generated by Django 5.2.3 on 2025-06-14 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_remove_dealership_city_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(blank=True, max_length=256, null=True)),
                ('auction_date', models.DateTimeField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=255, null=True)),
                ('older_model', models.IntegerField(blank=True, null=True)),
                ('stock_no', models.CharField(blank=True, max_length=255, null=True)),
                ('days_on_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('trim', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('cylinders', models.CharField(blank=True, max_length=255, null=True)),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('drivetrain', models.CharField(blank=True, max_length=255, null=True)),
                ('odometer', models.CharField(blank=True, max_length=255, null=True)),
                ('unknown_mileage', models.IntegerField(blank=True, null=True)),
                ('title_absent', models.IntegerField(blank=True, null=True)),
                ('title_branded', models.IntegerField(blank=True, null=True)),
                ('mechanical_issue', models.IntegerField(blank=True, null=True)),
                ('frame_damage', models.IntegerField(blank=True, null=True)),
                ('factory_emissions_modified', models.IntegerField(blank=True, null=True)),
                ('driveability_issue', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_special', models.IntegerField(blank=True, null=True)),
                ('speciality_notes', models.TextField(blank=True, null=True)),
                ('expected_price', models.CharField(blank=True, max_length=255, null=True)),
                ('reserve_price', models.TextField(blank=True, null=True)),
                ('ready_to_sell', models.TextField(blank=True, null=True)),
                ('live_appraisal', models.TextField(blank=True, null=True)),
                ('auction_type', models.TextField(blank=True, db_comment='1 = start bidding $0 , 2 = start the bid at 50% of reserve price , 3 = $3,000 less than reserve price.', null=True)),
                ('rough', models.CharField(blank=True, max_length=255, null=True)),
                ('average', models.CharField(blank=True, max_length=255, null=True)),
                ('clean', models.CharField(blank=True, max_length=255, null=True)),
                ('blackbook_data', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, db_comment='0 = Pending\r\n1 = Inspector Assigned\r\n2 = Inspection started\r\n3 = Inspection Completed\r\n4 = On Auction\r\n5 = Waiting for Buyer Confirmation\r\n6 = Payment Pending\r\n7 = Paid\r\n8 = Delivered\r\n9 = Rejected (inspection)', null=True)),
                ('inspection_status', models.IntegerField(blank=True, null=True)),
                ('inspector_assigned', models.IntegerField(blank=True, null=True)),
                ('inspected_date', models.DateField(blank=True, null=True)),
                ('inspector_reject_reason', models.TextField(blank=True, null=True)),
                ('is_sold', models.IntegerField(blank=True, null=True)),
                ('auction_won_id', models.IntegerField(blank=True, null=True)),
                ('buyer_id', models.IntegerField(blank=True, null=True)),
                ('buyer_confirmed', models.IntegerField(blank=True, null=True)),
                ('payment_on_clearance', models.IntegerField(blank=True, null=True)),
                ('payment_received', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('arbitration_expire_date', models.DateField(blank=True, null=True)),
                ('title_delivery_location', models.IntegerField(blank=True, null=True)),
                ('vehicle_delivery_location', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('transportation_taken', models.IntegerField(blank=True, null=True)),
                ('transport_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('arbitration_taken', models.IntegerField(blank=True, db_comment='For extended arbitration 0f 30 days', null=True)),
                ('arbitration_claim_requested', models.IntegerField(blank=True, db_comment='if buyer claim for arbitration', null=True)),
                ('arbitration_ticket_id', models.CharField(blank=True, db_comment='Ticket ID', max_length=255, null=True)),
                ('speciality_approval', models.IntegerField(blank=True, db_comment='1=approved 2=rejected', null=True)),
                ('speciality_ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_delivered', models.IntegerField()),
                ('via_api', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_requests', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to='users.dealership')),
                ('inspection_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_requests', to='users.dealerlocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inspection Requests',
            },
        ),
    ]
