# Generated by Django 5.2.3 on 2025-06-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspector_state_inspectorweekschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
