# Generated by Django 5.2.3 on 2025-06-28 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_inspectionrequest_status'),
        ('users', '0011_alter_role_created_by_alter_role_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSampleImages',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_sample_images', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspection_sample_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInspectionReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exterior', models.TextField(blank=True, null=True)),
                ('interior', models.TextField(blank=True, null=True)),
                ('mechanical', models.TextField(blank=True, null=True)),
                ('demage_and_rust', models.TextField(blank=True, null=True)),
                ('wheels', models.TextField(blank=True, null=True)),
                ('warning_lights', models.TextField(blank=True, null=True)),
                ('frame', models.TextField(blank=True, null=True)),
                ('drivability', models.TextField(blank=True, null=True)),
                ('yellow', models.IntegerField(blank=True, null=True)),
                ('red', models.IntegerField(blank=True, null=True)),
                ('green', models.IntegerField(blank=True, null=True)),
                ('purple', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='users.dealership')),
                ('inspector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='inspections.inspector')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='inspections.inspectionrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspection_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Inspection Report',
                'verbose_name_plural': 'Vehicle Inspection Reports',
            },
        ),
    ]
