# Generated by Django 5.2.4 on 2025-07-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspectionsampleimages_vehicleinspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequest',
            name='flood_damage',
            field=models.IntegerField(default=0),
        ),
    ]
