# Generated by Django 5.2.4 on 2025-07-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspectionrequest_flood_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequest',
            name='auction_status',
            field=models.IntegerField(default=0),
        ),
    ]
