# Generated by Django 5.2.4 on 2025-07-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_inspectionrequest_auction_status'),
        ('users', '0013_alter_dealership_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='buyer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_inspection_requests', to='users.dealership'),
        ),
    ]
