# Generated by Django 5.2.4 on 2025-07-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_alter_inspectionrequest_buyer_id'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='transport_job_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation.transportationjob'),
        ),
    ]
