# Generated by Django 5.2.4 on 2025-07-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionwon'),
        ('inspections', '0009_alter_inspectionrequest_transport_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrequest',
            name='has_blue',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionrequest',
            name='has_green',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionrequest',
            name='has_red',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionrequest',
            name='has_yellow',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='auction_won_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auctionwon'),
        ),
    ]
