# Generated by Django 5.2.4 on 2025-08-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_inspectionrequest_has_blue_and_more'),
        ('users', '0014_remove_transporter_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=765, null=True)),
                ('value', models.CharField(blank=True, max_length=765, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='title_delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_delivery_location_inspection_request', to='users.dealerlocation'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='vehicle_delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_delivery_location_inspection_request', to='users.dealerlocation'),
        ),
    ]
