# Generated by Django 5.2.4 on 2025-08-06 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_carattributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('recipient_first_name', models.CharField(blank=True, max_length=765, null=True)),
                ('recipient_last_name', models.CharField(blank=True, max_length=765, null=True)),
                ('recipient_email', models.CharField(blank=True, max_length=765, null=True)),
                ('recipient_contact_number', models.CharField(blank=True, max_length=765, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_deliveries', to='inspections.inspectionrequest')),
            ],
            options={
                'verbose_name': 'Manual Delivery',
                'verbose_name_plural': 'Manual Deliveries',
            },
        ),
        migrations.CreateModel(
            name='ManualAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='manual-attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('manual_delivery_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='inspections.manualdelivery')),
            ],
            options={
                'verbose_name': 'Manual Attachment',
                'verbose_name_plural': 'Manual Attachments',
            },
        ),
    ]
