# Generated by Django 5.2.4 on 2025-08-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitration', '0001_initial'),
        ('inspections', '0012_manualdelivery_manualattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='arbitration_ticket_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbitration.ticketarbitrationdata'),
        ),
    ]
