from django.urls import path
from auctions.api.v1.views import (
    UpcomingAuctionsListAPIView,
    UpcomingAuctionRetrieveAPIView,
    AuctionsRunListAPIView,
    AdminSendToAuctionAPIView,
    AuctionsLiveListAPIView,
    AuctionsWonListAPIView,
    MarketplaceListAPIView,
    MarketplaceDetailAPIView,
    AuctionBuyingCurrentListAPIView,
    AuctionBuyingInNegotiationListAPIView,
    AuctionBuyingWonListAPIView,
    CreateAuctionBidCreateAPIView,
    AuctionSellingCurrentListAPIView,
    AuctionSellingInNegotiationListAPIView,
    AuctionSellingSoldListAPIView,
    CreateAuctionOfferAPIView,
    OfferNowListAPIView,
    SoldListAPIView,
    AcceptNegotiationBidAPIView,
    AcceptNegotiationOfferAPIView,
    BuyerConfirmationAPIView,
    SellerNegotiationUpdateAPIView,
    BuyerNegotiationUpdateAPIView,
    BuyNowAPIView,
    CreateAuctionProxyAPIView,
    StopAuctionLiveAPIView,
    CheckoutSessionCreateAPIView,
)


urlpatterns = [
    path("upcoming/", UpcomingAuctionsListAPIView.as_view(), name="upcoming_auctions"),
    path("upcoming/<int:pk>/", UpcomingAuctionRetrieveAPIView.as_view(), name="upcoming_auction_detail"),
    path("on-run-list/", AuctionsRunListAPIView.as_view(), name="run_list_auctions"),
    path("admin/send-to-auctions/", AdminSendToAuctionAPIView.as_view(), name="admin_send_to_auctions"),
    path("live/", AuctionsLiveListAPIView.as_view(), name="auctions_live_list"),
    path("won/", AuctionsWonListAPIView.as_view(), name="auctions_won_list"),
    path("marketplace/", MarketplaceListAPIView.as_view(), name="marketplace_auctions_list"),
    path("marketplace/<int:pk>/", MarketplaceDetailAPIView.as_view(), name="marketplace_auction_detail"),
    path("current-buying/", AuctionBuyingCurrentListAPIView.as_view(), name="auction_buying_current_list"),
    path("buying-in-negotiation/", AuctionBuyingInNegotiationListAPIView.as_view(), name="auction_buying_in_negotiation_list"),
    path("buying-won/", AuctionBuyingWonListAPIView.as_view(), name="auction_buying_won_list"),
    path("create-bid/", CreateAuctionBidCreateAPIView.as_view(), name="auction_create_bid"),
    path("current-selling/", AuctionSellingCurrentListAPIView.as_view(), name="auction_selling_current_list"),
    path("selling-in-negotiation/", AuctionSellingInNegotiationListAPIView.as_view(), name="auction_selling_in_negotiation"),
    path("selling-won/", AuctionSellingSoldListAPIView.as_view(), name="auction_selling_sold_list"),
    path("create-offer/", CreateAuctionOfferAPIView.as_view(), name="auction_create_offer"),
    path("offer-now/", OfferNowListAPIView.as_view(), name="auction_offer_now"),
    path("sold/", SoldListAPIView.as_view(), name="auctions_sold_list"),
    path("accept-bid/", AcceptNegotiationBidAPIView.as_view(), name="auction_accept_bid"),
    path("accept-offer/", AcceptNegotiationOfferAPIView.as_view(), name="auction_accept_offer"),
    path("buyer-confirmation/", BuyerConfirmationAPIView.as_view(), name="auction_buyer_confirmation"),
    path("seller/update-negotiation/<str:auction_id>/", SellerNegotiationUpdateAPIView.as_view(), name="update_seller_negotiation"),
    path("buyer/update-negotiation/<str:auction_id>/", BuyerNegotiationUpdateAPIView.as_view(), name="update_buyer_negotiation"),
    path("buy-now/", BuyNowAPIView.as_view(), name="buy_now"),
    path("create-proxy/", CreateAuctionProxyAPIView.as_view(), name="create_proxy"),
    path("stop/<str:auction_id>/", StopAuctionLiveAPIView.as_view(), name="stop_live_auction"),
    path("payment/checkout-session/", CheckoutSessionCreateAPIView.as_view(), name="stripe_checkout_session"),
]
