version: '3.3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: awdauctions
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: awd_auctions
      MYSQL_USER: mysql
      MYSQL_PASSWORD: awdauctions
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - project_static_volume:/app/static
      - project_media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=awd_auctions
      - DB_USER=mysql
      - DB_PASSWORD=awdauctions

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
  project_static_volume:
  project_media_volume:
