# Generated by Django 5.2.4 on 2025-07-06 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0005_inspectionsampleimages_vehicleinspectionreport'),
        ('users', '0012_dealership_is_active_role_is_active_user_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('last_bid_id', models.IntegerField(blank=True, null=True)),
                ('last_proxy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_proxy_buyer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_price', models.FloatField(blank=True, null=True)),
                ('reserve_price', models.TextField(blank=True, null=True)),
                ('ready_to_sell', models.TextField(blank=True, null=True)),
                ('live_appraisal', models.TextField(blank=True, null=True)),
                ('auction_type', models.TextField(blank=True, db_comment='1 = start bidding $0 , 2 = start the bid at 50% of reserve price , 3 = $3,000 less than reserve price.', null=True)),
                ('bid_start_from_price', models.CharField(max_length=255)),
                ('won_type', models.IntegerField(blank=True, db_comment='1= Bid, 2= Proxy Bid, 3 = Buy Now', null=True)),
                ('won_by_id', models.CharField(blank=True, max_length=255, null=True)),
                ('won_bid_id', models.CharField(blank=True, max_length=255, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('credit_use_for_inspection_fee', models.IntegerField(blank=True, null=True)),
                ('credit_use_for_selling_fee', models.IntegerField(blank=True, null=True)),
                ('credit_use_for_buying', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auctions', to=settings.AUTH_USER_MODEL)),
                ('dealer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='users.dealership')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='inspections.inspectionrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auctions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
