# Generated by Django 5.2.4 on 2025-07-12 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('inspections', '0008_alter_inspectionrequest_buyer_id'),
        ('users', '0013_alter_dealership_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBids',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auction_id', models.CharField(blank=True, max_length=256, null=True)),
                ('bid', models.IntegerField(blank=True, null=True)),
                ('last_bid', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('is_expired', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bids', to='users.dealership')),
                ('buyer_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_user_auction_bids', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auction_bids', to=settings.AUTH_USER_MODEL)),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bids', to='inspections.inspectionrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auction_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Bid',
                'verbose_name_plural': 'Auction Bids',
            },
        ),
        migrations.AlterField(
            model_name='auctions',
            name='last_bid_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auctionbids'),
        ),
        migrations.CreateModel(
            name='AuctionNegotiations',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_type', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('is_accepted', models.IntegerField(blank=True, null=True)),
                ('is_rejected', models.IntegerField(blank=True, null=True)),
                ('is_expire', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bid_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_negotiations', to='auctions.auctionbids')),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_auction_negotiations', to='users.dealership')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auction_negotiations', to=settings.AUTH_USER_MODEL)),
                ('dealer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_auction_negotiations', to='users.dealership')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_negotiations', to='inspections.inspectionrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auction_negotiations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Negotiation',
                'verbose_name_plural': 'Auction Negotiations',
            },
        ),
        migrations.CreateModel(
            name='AuctionOffers',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_type', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('is_accepted', models.IntegerField(blank=True, null=True)),
                ('is_rejected', models.IntegerField(blank=True, null=True)),
                ('is_expire', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_auction_offers', to='users.dealership')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auction_offers', to=settings.AUTH_USER_MODEL)),
                ('dealer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_auction_offers', to='users.dealership')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_offers', to='inspections.inspectionrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auction_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Offer',
                'verbose_name_plural': 'Auction Offers',
            },
        ),
        migrations.CreateModel(
            name='AuctionProxies',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_amount', models.IntegerField(blank=True, null=True)),
                ('bid_amount', models.IntegerField(db_comment='this is the last heighest bid amount,if won by proxy then this amount will consider to pay.')),
                ('is_expire', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_auction_proxies', to='users.dealership')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auction_proxies', to=settings.AUTH_USER_MODEL)),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_proxies', to='inspections.inspectionrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auction_proxies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Proxy',
                'verbose_name_plural': 'Auction Proxies',
            },
        ),
    ]
