# Generated by Django 5.2.4 on 2025-07-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionbids_alter_auctions_last_bid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='last_proxy_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auctionproxies'),
        ),
    ]
