# Generated by Django 5.2.4 on 2025-07-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctions_last_proxy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionoffers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
