# Generated by Django 5.2.4 on 2025-07-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionoffers_id'),
        ('users', '0013_alter_dealership_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='last_proxy_buyer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_buyer_auctions', to='users.dealership'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='won_bid_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction', to='auctions.auctionbids'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='won_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_auctions', to='users.dealership'),
        ),
    ]
