# Generated by Django 5.2.4 on 2025-07-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctions_last_proxy_buyer_id_and_more'),
        ('inspections', '0008_alter_inspectionrequest_buyer_id'),
        ('users', '0013_alter_dealership_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionWon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('bid_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_price', models.IntegerField(blank=True, null=True)),
                ('buyer_confirmation', models.IntegerField(blank=True, null=True)),
                ('won_type', models.IntegerField(blank=True, db_comment='1= Bid, 2= Proxy Bid, 3 = Buy Now', null=True)),
                ('is_expired', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_auctions_won', to='users.dealership')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_won', to='inspections.inspectionrequest')),
            ],
            options={
                'verbose_name': 'Auction Won',
                'verbose_name_plural': 'Auctions Won',
            },
        ),
    ]
