# Generated by Django 5.2.4 on 2025-07-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionwon'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionnegotiations',
            name='changed_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionnegotiations',
            name='price_change_requested_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionnegotiations',
            name='price_change_requested_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionoffers',
            name='price_change_requested_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionoffers',
            name='price_change_requested_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
