# Generated by Django 5.2.4 on 2025-07-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionbids_id_alter_auctionnegotiations_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionwon',
            name='bid_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
