# Generated by Django 5.2.4 on 2025-07-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_city_created_by_alter_city_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
