# Generated by Django 5.2.4 on 2025-07-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0008_alter_inspectionrequest_buyer_id'),
        ('users', '0013_alter_dealership_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationChargesSlab',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('km_range_start', models.CharField(blank=True, max_length=256, null=True)),
                ('km_range_end', models.CharField(blank=True, max_length=256, null=True)),
                ('buyer_charges_per_km', models.CharField(blank=True, max_length=255, null=True)),
                ('transporter_charges_per_km', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transportation Charges Slab',
                'verbose_name_plural': 'Transportation Charges Slab',
            },
        ),
        migrations.CreateModel(
            name='TransportationJobTrackingStatusMsg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('msg', models.CharField(max_length=255)),
                ('transporter_msg', models.CharField(max_length=255)),
                ('buyer_msg', models.CharField(max_length=255)),
                ('seller_msg', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Transportation Job Tracking Status Msg',
                'verbose_name_plural': 'Transportation Job Tracking Status Msgs',
            },
        ),
        migrations.CreateModel(
            name='TransportationJob',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.CharField(blank=True, max_length=255, null=True)),
                ('charges_per_mile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_dual_gate_key', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_dual_gate_key', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('tracking_status', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_transportation_jobs', to='users.dealership')),
                ('dealer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_transportation_jobs', to='users.dealership')),
                ('drop_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_transportation_jobs', to='users.dealerlocation')),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_transportation_jobs', to='users.dealerlocation')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_jobs', to='inspections.inspectionrequest')),
                ('transportation_slab_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_jobs', to='transportation.transportationchargesslab')),
                ('transporter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='users.transporter')),
            ],
            options={
                'verbose_name': 'Transportation Job',
                'verbose_name_plural': 'Transportation Jobs',
            },
        ),
        migrations.CreateModel(
            name='TransportationJobTracking',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_job_tracking', to='transportation.transportationjob')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation_job_tracking', to='inspections.inspectionrequest')),
            ],
            options={
                'verbose_name': 'Transportation Job Tracking',
                'verbose_name_plural': 'Transportation Job Tracking',
            },
        ),
        migrations.CreateModel(
            name='TransporterDocument',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('transporter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.transporter')),
            ],
            options={
                'verbose_name': 'Transportation Document',
                'verbose_name_plural': 'Transportation Documents',
            },
        ),
    ]
