# Generated by Django 5.2.4 on 2025-07-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationchargesslab',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
