# Generated by Django 5.2.4 on 2025-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_transportationchargesslab_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporterdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='transportation'),
        ),
        migrations.AlterField(
            model_name='transporterdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
