# Generated by Django 5.2.4 on 2025-08-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_alter_transportationchargesslab_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationjob',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transportationjob',
            name='tracking_status',
            field=models.IntegerField(default=0),
        ),
    ]
