# Generated by Django 5.2.4 on 2025-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_alter_transportationjob_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationjob',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transportationjob',
            name='distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
