# Generated by Django 5.2.4 on 2025-08-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_transportationjob_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationchargesslab',
            name='km_range_end',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transportationchargesslab',
            name='km_range_start',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
