# Generated by Django 5.2.1 on 2025-05-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stripe_account_id', models.TextField(blank=True, null=True)),
                ('dealership_type', models.IntegerField(blank=True, null=True)),
                ('dealership_interest', models.IntegerField(blank=True, null=True)),
                ('seller_fees_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cars_in_stock', models.IntegerField(blank=True, null=True)),
                ('no_of_locations', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dealership_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ext', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=255, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('dealer_license', models.CharField(blank=True, max_length=255, null=True)),
                ('business_license', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('text_update', models.IntegerField(blank=True, null=True)),
                ('password_created', models.IntegerField(blank=True, null=True)),
                ('retail_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('applied_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ext', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transporter_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.dealership'),
        ),
        migrations.AddField(
            model_name='user',
            name='transporter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.transporter'),
        ),
    ]
