# Generated by Django 5.2.1 on 2025-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dealership_transporter_remove_user_dealer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='business_licence'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='dealer_license',
            field=models.FileField(blank=True, null=True, upload_to='dealer_licence'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='retail_certificate',
            field=models.FileField(blank=True, null=True, upload_to='retail_certificates'),
        ),
    ]
