# Generated by Django 5.2.1 on 2025-05-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='contact_preference',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Text', 'Text'), ('Email', 'Email')], default='Phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.role'),
        ),
    ]
