# Generated by Django 5.2.1 on 2025-06-02 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_dealership_contact_preference_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='approved',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dealerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dealerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
