# Generated by Django 5.2.3 on 2025-06-10 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_dealership_approved_and_more'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='state_name',
        ),
        migrations.AddField(
            model_name='dealership',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerships', to='utils.city'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerships', to='utils.state'),
        ),
        migrations.CreateModel(
            name='DealerLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('state_id', models.BigIntegerField(blank=True, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('dealer_license', models.TextField(blank=True, null=True)),
                ('business_license', models.TextField(blank=True, null=True)),
                ('retail_certificate', models.TextField(blank=True, null=True)),
                ('is_main', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.IntegerField(blank=True, null=True)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dealer_location', to=settings.AUTH_USER_MODEL)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_locations', to='users.dealership')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dealer_location', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dealer Locations',
            },
        ),
    ]
