# Generated by Django 5.2.3 on 2025-06-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_dealership_city_name_and_more'),
        ('utils', '0003_alter_city_created_by_alter_city_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerlocation',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='dealerlocation',
            name='state_id',
        ),
        migrations.AddField(
            model_name='dealerlocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_locations', to='utils.city'),
        ),
        migrations.AddField(
            model_name='dealerlocation',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_locations', to='utils.state'),
        ),
        migrations.AlterField(
            model_name='dealerlocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
