# Generated by Django 5.2.4 on 2025-07-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_role_created_by_alter_role_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
