# Generated by Django 5.2.4 on 2025-07-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_dealership_is_active_role_is_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
