# Generated by Django 5.2.4 on 2025-07-22 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_dealership_approved'),
        ('utils', '0004_alter_city_status_alter_country_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='transporter',
            name='state_name',
        ),
        migrations.AddField(
            model_name='transporter',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporters', to='utils.city'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporters', to='utils.state'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transporters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_transporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
